### ISSUE TITLE
UI Doesn't scale properly for different devices

### ISSUE THREAD

**Issue by CCrawfordUOP** [uop-libraries/CreativeResponse2022#193]
#### Acceptance Criteria
- [ ] UI Scales for different phone screen sizes

#### Tasks
- [ ] Go into every scene and figure out which anchor to set center so it matches for any phone screen size

**Comment by cfines** [comment]
We messed up real bad, from what I can see we manually set the positions of every object on the screen specifically to the Google Pixel resolution. I'm trying to think of a way to make that transferable across all other resolutions without manually repositioning everything. Otherwise I'm going to have to do that for every. single. page.

**Comment by cfines** [comment]
Update: I think I figured it out. I still have to update the canvas scaler and the main parent objects, but I don't have to reposition everything so that's good.

**Comment by cfines** [comment]
Everything should be scaled properly now, no matter the **portrait** resolution... but it's not perfect. It still conforms to the reference resolution of the Google Pixel (1080x2400) and we never considered widening the borders and other images and text based on resolution (like spacing placements and widening text boxes with a wider resolution), so everything simply stays the same size in their same position as if it were still the Google Pixel resolution. However this is only apparent with tablet resolutions (inherently wider), and will be (hopefully) unnoticed with standard phone aspect ratios. The Fixing-Scaling branch is now ready to merge.
